### PR TITLE
fix sentinel warnings when compiling with dovecot 3.15

### PR DESCRIPTION
**Pull request by a16bitsysop**

### CODE REVIEW

**Comment by jrse** [comment]
thanks for contributing. will take care of it.

**Comment by a16bitsysop** [comment]
okay, thanks it currently won't compile with dovecot 2.3.18 either there are lots of these errors:

```
In file included from dict-rados.cpp:42:
dict-rados.h:47:24: error: macro "DOVECOT_PREREQ" requires 3 arguments, but only 2 given
   47 | #if DOVECOT_PREREQ(2, 3)
      |                        ^
In file included from /usr/include/dovecot/lib.h:27,
                 from dovecot-dict.h:23,
                 from dict-rados.cpp:36:
/usr/include/dovecot/macros.h:237: note: macro "DOVECOT_PREREQ" defined here
  237 | #define DOVECOT_PREREQ(maj, min, micro) \
```
